### PR TITLE
Token based authentication using JWT

### PR DESCRIPTION
**Pull request by gastonmancini**
Hey @mravinale ! 
I've changed the old authentication method (server based) with a token based authentication using JWT. Using this new approach we avoid storing the user logged info on the server and we made it stateless. We have a lot of advantages doing this such as scalability, CORS and CSRF. 
I've used [this json web token implementation](https://www.npmjs.com/package/jsonwebtoken), that was developed and maintained by the [auth0](https://auth0.com/) team -owners of [JWT.io](http://jwt.io/).
Some of the biggest changes made: remove all the sessions related stuff, add an angularJS interceptor for managing the tokens and change the auth services in both backend and frontend.

### CODE REVIEW

**Comment by AlphaGit** [comment]
:+1:

**Comment by gastonmancini** [comment]
@mravinale please don't merge this PR yet. Wait until I add some tests, I will be working with Mocha and Protractor.

**Comment by gastonmancini** [comment]
Tests added

**Comment by mravinale** [comment]
@gastonmancini I think this needs a rebase:  `git rebase MakingSense/master` in order to update the branch for merging, or merge the latest changes to your branch

**Comment by gastonmancini** [comment]
@mravinale merge done :+1:

**Comment by gastonmancini** [comment]
Pull request fixes done

**Comment by mravinale** [comment]
:+1:

**Pull request merged**
